name: Operator action
on:
  push:
     branches:
       - action/sign-index
#    tags:
#      - v*

jobs:
  test-webhook:
    runs-on: ubuntu-latest
    name: Test procedure
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: test-webhook
        uses:  ./
        env:
          webhook_type: 'json-extended'
          webhook_url: 'https://api.enterprise.redhat.com/hydra/umb-bridge/v1/publish'
          webhook_secret: ${{ secrets.INDEX_SIGN_WEBHOOK }}
          data: '{"index_image": "quay.io/redhat/redhat----community-operator-index:v4.6", "index_image_resolved": "quay.io/redhat/redhat----community-operator-index@sha256:041b99c56f7c61a0e0e0708482ff43719e96169b5502297d62d01cb39176592c"}'
#          continue-on-error: true
