name: Operator action
on:
  push:
     branches:
       - action/sign-index
#    tags:
#      - v*

jobs:
  test-webhook:
    runs-on: ubuntu-latest
    name: Test procedure
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - id: test-webhook
#        uses:  ./
#        env:
#          webhook_type: 'json-extended'
#          webhook_url: 'https://api.enterprise.redhat.com/hydra/umb-bridge/v1/publish'
#          webhook_secret: ${{ secrets.INDEX_SIGN_WEBHOOK }}
#          data: '{"index_image": "quay.io/redhat/redhat----community-operator-index:v4.6", "index_image_resolved": "quay.io/redhat/redhat----community-operator-index@sha256:041b99c56f7c61a0e0e0708482ff43719e96169b5502297d62d01cb39176592c"}'
##          continue-on-error: true
      - name: Webhook Action test 5
        uses: distributhor/workflow-webhook@v1
        env:
           webhook_type: 'json-extended'
#           webhook_url: 'https://api.enterprise.redhat.com/hydra/umb-bridge/v1/publish'
#           webhook_url: 'https://access.redhat.com/hydra/umb-bridge/v1/publish'
           webhook_url: 'https://access.redhat.com/hydra/proxy/umb-bridge-qa/v1/publish'
           webhook_secret: ${{ secrets.INDEX_SIGN_WEBHOOK_QA }}
           data: '{"index_image": "quay.io/redhat/redhat----community-operator-index:v4.8", "index_image_resolved": "quay.io/redhat/redhat----community-operator-index@sha256:a885686bf2795c418b82868fe54e37f76646b4a94ccf16ae1e8eeeea9b1d1a29"}'
#        continue-on-error: true